[tools]
go = "1.26.5"
node = "24.18.0"
"npm:@commitlint/cli" = "21.2.1"
"npm:@commitlint/config-conventional" = "21.2.0"
kubebuilder = "4.15.0"
kind = "0.32.0"
skaffold = "2.23.0"
kubectl = "1.36.2"
kustomize = "5.8.1"
helm = "4.2.3"
task = "3.52.0"
"aqua:norwoodj/helm-docs" = "1.14.2"
uv = "0.11.30"
dotnet = "10.0.300"
"dotnet:nbgv" = "3.9.50"
golangci-lint = "2.12.2"
omnictl = "1.9.3"
"go:sigs.k8s.io/controller-tools/cmd/controller-gen" = "v0.21.0"
"go:sigs.k8s.io/controller-runtime/tools/setup-envtest" = "release-0.23"

[settings]
experimental = true

[env]
KIND_CLUSTER = "omni-cluster-operator-dev"
E2E_KIND_CLUSTER = "omni-cluster-operator-test-e2e"
OMNI_OPERATOR_IMG = "omni-cluster-operator:dev"
CERT_MANAGER_VERSION = "v1.20.2"
ENVTEST_K8S_VERSION = "1.35"
NBGV_VERSION = "3.9.50"
OMNI_NAMESPACE = "omni-system"
OMNI_VERSION = "v1.8.0"
OMNI_CHART_VERSION = "2.8.0"
OMNI_LIVE_ENDPOINT = "http://omni.omni-system.svc.cluster.local:8080"
OMNI_LIVE_SERVICE_ACCOUNT_KEY_FILE = ".local/omni/service-account.key"
LIVE_OMNI_OPERATOR_NAMESPACE = "omni-cluster-operator-system"
