{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "omni-cluster-operator.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "omni-cluster-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "omni-cluster-operator.servingCertName" . }}
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omnicilium
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomnicilium-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omniciliums
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omnicluster
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomnicluster-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omniclusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omniclusteraddon
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomniclusteraddon-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omniclusteraddons
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omniconnection
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomniconnection-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omniconnections
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omnicontrolplane
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomnicontrolplane-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omnicontrolplanes
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omnimachine
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomnimachine-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omnimachines
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "omni-cluster-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-omni-texashpc-com-v1alpha1-omniworkers
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    name: vomniworkers-v1alpha1.kb.io
    rules:
      - apiGroups:
          - omni.texashpc.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - omniworkers
    sideEffects: None
{{- end }}
