---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omnisecretsync-admin-role
rules:
  - apiGroups:
      - omni.texashpc.com
    resources:
      - omnisecretsyncs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - omni.texashpc.com
    resources:
      - omnisecretsyncs/status
    verbs:
      - get
      - patch
      - update
