---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: omnisecretsync-admin-role
rules:
  - apiGroups:
      - omni.texashpc.com
    resources:
      - omnisecretsyncs
    verbs:
      - '*'
  - apiGroups:
      - omni.texashpc.com
    resources:
      - omnisecretsyncs/status
    verbs:
      - get
