# This rule is not used by the project omni-cluster-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read/write access to omni.texashpc.com resources.
# This role is intended for users who need to manage these resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: omni-cluster-operator
    app.kubernetes.io/managed-by: kustomize
  name: omnihelmrelease-editor-role
rules:
- apiGroups:
  - omni.texashpc.com
  resources:
  - omnihelmreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omni.texashpc.com
  resources:
  - omnihelmreleases/status
  verbs:
  - get
