---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omni.texashpc.com
  resources:
  - omniclusters
  - omniconnections
  - omnicontrolplanes
  - omnihelmreleases
  - omnikubeconfigexports
  - omnimachines
  - omniworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omni.texashpc.com
  resources:
  - omniclusters/finalizers
  - omniconnections/finalizers
  - omnicontrolplanes/finalizers
  - omnihelmreleases/finalizers
  - omnikubeconfigexports/finalizers
  - omnimachines/finalizers
  - omniworkers/finalizers
  verbs:
  - update
- apiGroups:
  - omni.texashpc.com
  resources:
  - omniclusters/status
  - omniconnections/status
  - omnicontrolplanes/status
  - omnihelmreleases/status
  - omnikubeconfigexports/status
  - omnimachines/status
  - omniworkers/status
  verbs:
  - get
  - patch
  - update
