//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfiguration) DeepCopyInto(out *BackupConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfiguration.
func (in *BackupConfiguration) DeepCopy() *BackupConfiguration {
	if in == nil {
		return nil
	}
	out := new(BackupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeletePolicy) DeepCopyInto(out *ClusterDeletePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeletePolicy.
func (in *ClusterDeletePolicy) DeepCopy() *ClusterDeletePolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterDeletePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFeatures) DeepCopyInto(out *ClusterFeatures) {
	*out = *in
	if in.BackupConfiguration != nil {
		in, out := &in.BackupConfiguration, &out.BackupConfiguration
		*out = new(BackupConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFeatures.
func (in *ClusterFeatures) DeepCopy() *ClusterFeatures {
	if in == nil {
		return nil
	}
	out := new(ClusterFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatusFields) DeepCopyInto(out *CommonStatusFields) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatusFields.
func (in *CommonStatusFields) DeepCopy() *CommonStatusFields {
	if in == nil {
		return nil
	}
	out := new(CommonStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatusFields) DeepCopyInto(out *ConnectionStatusFields) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatusFields.
func (in *ConnectionStatusFields) DeepCopy() *ConnectionStatusFields {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Descriptors) DeepCopyInto(out *Descriptors) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Descriptors.
func (in *Descriptors) DeepCopy() *Descriptors {
	if in == nil {
		return nil
	}
	out := new(Descriptors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmReleaseKubeconfigSecretRef) DeepCopyInto(out *HelmReleaseKubeconfigSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmReleaseKubeconfigSecretRef.
func (in *HelmReleaseKubeconfigSecretRef) DeepCopy() *HelmReleaseKubeconfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(HelmReleaseKubeconfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigServiceAccountSpec) DeepCopyInto(out *KubeconfigServiceAccountSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigServiceAccountSpec.
func (in *KubeconfigServiceAccountSpec) DeepCopy() *KubeconfigServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigTargetSecretRef) DeepCopyInto(out *KubeconfigTargetSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigTargetSecretRef.
func (in *KubeconfigTargetSecretRef) DeepCopy() *KubeconfigTargetSecretRef {
	if in == nil {
		return nil
	}
	out := new(KubeconfigTargetSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesManifest) DeepCopyInto(out *KubernetesManifest) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = make([]v1.JSON, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesManifest.
func (in *KubernetesManifest) DeepCopy() *KubernetesManifest {
	if in == nil {
		return nil
	}
	out := new(KubernetesManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSpec) DeepCopyInto(out *KubernetesSpec) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]KubernetesManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSpec.
func (in *KubernetesSpec) DeepCopy() *KubernetesSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineClass) DeepCopyInto(out *MachineClass) {
	*out = *in
	out.Size = in.Size
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineClass.
func (in *MachineClass) DeepCopy() *MachineClass {
	if in == nil {
		return nil
	}
	out := new(MachineClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineInstallSpec) DeepCopyInto(out *MachineInstallSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineInstallSpec.
func (in *MachineInstallSpec) DeepCopy() *MachineInstallSpec {
	if in == nil {
		return nil
	}
	out := new(MachineInstallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSetSpecFields) DeepCopyInto(out *MachineSetSpecFields) {
	*out = *in
	in.Descriptors.DeepCopyInto(&out.Descriptors)
	if in.Machines != nil {
		in, out := &in.Machines, &out.Machines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MachineClass != nil {
		in, out := &in.MachineClass, &out.MachineClass
		*out = new(MachineClass)
		**out = **in
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemExtensions != nil {
		in, out := &in.SystemExtensions, &out.SystemExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KernelArgs != nil {
		in, out := &in.KernelArgs, &out.KernelArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSetSpecFields.
func (in *MachineSetSpecFields) DeepCopy() *MachineSetSpecFields {
	if in == nil {
		return nil
	}
	out := new(MachineSetSpecFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniAuthSpec) DeepCopyInto(out *OmniAuthSpec) {
	*out = *in
	out.ServiceAccountSecretRef = in.ServiceAccountSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniAuthSpec.
func (in *OmniAuthSpec) DeepCopy() *OmniAuthSpec {
	if in == nil {
		return nil
	}
	out := new(OmniAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniCluster) DeepCopyInto(out *OmniCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniCluster.
func (in *OmniCluster) DeepCopy() *OmniCluster {
	if in == nil {
		return nil
	}
	out := new(OmniCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniClusterList) DeepCopyInto(out *OmniClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniClusterList.
func (in *OmniClusterList) DeepCopy() *OmniClusterList {
	if in == nil {
		return nil
	}
	out := new(OmniClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniClusterSpec) DeepCopyInto(out *OmniClusterSpec) {
	*out = *in
	in.Descriptors.DeepCopyInto(&out.Descriptors)
	in.ConnectionRef.DeepCopyInto(&out.ConnectionRef)
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	out.Talos = in.Talos
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(ClusterFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemExtensions != nil {
		in, out := &in.SystemExtensions, &out.SystemExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KernelArgs != nil {
		in, out := &in.KernelArgs, &out.KernelArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.DeletePolicy = in.DeletePolicy
	out.SyncInterval = in.SyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniClusterSpec.
func (in *OmniClusterSpec) DeepCopy() *OmniClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OmniClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniClusterStatus) DeepCopyInto(out *OmniClusterStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
	out.ConnectionStatusFields = in.ConnectionStatusFields
	in.SyncStatusFields.DeepCopyInto(&out.SyncStatusFields)
	if in.WorkersRefs != nil {
		in, out := &in.WorkersRefs, &out.WorkersRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MachineRefs != nil {
		in, out := &in.MachineRefs, &out.MachineRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniClusterStatus.
func (in *OmniClusterStatus) DeepCopy() *OmniClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OmniClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniConnection) DeepCopyInto(out *OmniConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniConnection.
func (in *OmniConnection) DeepCopy() *OmniConnection {
	if in == nil {
		return nil
	}
	out := new(OmniConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniConnectionList) DeepCopyInto(out *OmniConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniConnectionList.
func (in *OmniConnectionList) DeepCopy() *OmniConnectionList {
	if in == nil {
		return nil
	}
	out := new(OmniConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniConnectionSpec) DeepCopyInto(out *OmniConnectionSpec) {
	*out = *in
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniConnectionSpec.
func (in *OmniConnectionSpec) DeepCopy() *OmniConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(OmniConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniConnectionStatus) DeepCopyInto(out *OmniConnectionStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
	out.ConnectionStatusFields = in.ConnectionStatusFields
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniConnectionStatus.
func (in *OmniConnectionStatus) DeepCopy() *OmniConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(OmniConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniControlPlane) DeepCopyInto(out *OmniControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniControlPlane.
func (in *OmniControlPlane) DeepCopy() *OmniControlPlane {
	if in == nil {
		return nil
	}
	out := new(OmniControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniControlPlaneList) DeepCopyInto(out *OmniControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniControlPlaneList.
func (in *OmniControlPlaneList) DeepCopy() *OmniControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(OmniControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniControlPlaneSpec) DeepCopyInto(out *OmniControlPlaneSpec) {
	*out = *in
	in.MachineSetSpecFields.DeepCopyInto(&out.MachineSetSpecFields)
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	if in.BootstrapSpec != nil {
		in, out := &in.BootstrapSpec, &out.BootstrapSpec
		*out = new(BootstrapSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniControlPlaneSpec.
func (in *OmniControlPlaneSpec) DeepCopy() *OmniControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(OmniControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniControlPlaneStatus) DeepCopyInto(out *OmniControlPlaneStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniControlPlaneStatus.
func (in *OmniControlPlaneStatus) DeepCopy() *OmniControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(OmniControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniHelmChartSpec) DeepCopyInto(out *OmniHelmChartSpec) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniHelmChartSpec.
func (in *OmniHelmChartSpec) DeepCopy() *OmniHelmChartSpec {
	if in == nil {
		return nil
	}
	out := new(OmniHelmChartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniHelmRelease) DeepCopyInto(out *OmniHelmRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniHelmRelease.
func (in *OmniHelmRelease) DeepCopy() *OmniHelmRelease {
	if in == nil {
		return nil
	}
	out := new(OmniHelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniHelmRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniHelmReleaseList) DeepCopyInto(out *OmniHelmReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniHelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniHelmReleaseList.
func (in *OmniHelmReleaseList) DeepCopy() *OmniHelmReleaseList {
	if in == nil {
		return nil
	}
	out := new(OmniHelmReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniHelmReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniHelmReleaseSpec) DeepCopyInto(out *OmniHelmReleaseSpec) {
	*out = *in
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	out.KubeconfigSecretRef = in.KubeconfigSecretRef
	in.Chart.DeepCopyInto(&out.Chart)
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniHelmReleaseSpec.
func (in *OmniHelmReleaseSpec) DeepCopy() *OmniHelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(OmniHelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniHelmReleaseStatus) DeepCopyInto(out *OmniHelmReleaseStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessTime != nil {
		in, out := &in.LastSuccessTime, &out.LastSuccessTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniHelmReleaseStatus.
func (in *OmniHelmReleaseStatus) DeepCopy() *OmniHelmReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(OmniHelmReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniKubeconfigExport) DeepCopyInto(out *OmniKubeconfigExport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniKubeconfigExport.
func (in *OmniKubeconfigExport) DeepCopy() *OmniKubeconfigExport {
	if in == nil {
		return nil
	}
	out := new(OmniKubeconfigExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniKubeconfigExport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniKubeconfigExportList) DeepCopyInto(out *OmniKubeconfigExportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniKubeconfigExport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniKubeconfigExportList.
func (in *OmniKubeconfigExportList) DeepCopy() *OmniKubeconfigExportList {
	if in == nil {
		return nil
	}
	out := new(OmniKubeconfigExportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniKubeconfigExportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniKubeconfigExportSpec) DeepCopyInto(out *OmniKubeconfigExportSpec) {
	*out = *in
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	out.TargetSecretRef = in.TargetSecretRef
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	out.TTL = in.TTL
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniKubeconfigExportSpec.
func (in *OmniKubeconfigExportSpec) DeepCopy() *OmniKubeconfigExportSpec {
	if in == nil {
		return nil
	}
	out := new(OmniKubeconfigExportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniKubeconfigExportStatus) DeepCopyInto(out *OmniKubeconfigExportStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
	out.ConnectionStatusFields = in.ConnectionStatusFields
	if in.ServiceAccountGroups != nil {
		in, out := &in.ServiceAccountGroups, &out.ServiceAccountGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpirationTime != nil {
		in, out := &in.ExpirationTime, &out.ExpirationTime
		*out = (*in).DeepCopy()
	}
	if in.NextRotationTime != nil {
		in, out := &in.NextRotationTime, &out.NextRotationTime
		*out = (*in).DeepCopy()
	}
	if in.LastRotationTime != nil {
		in, out := &in.LastRotationTime, &out.LastRotationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniKubeconfigExportStatus.
func (in *OmniKubeconfigExportStatus) DeepCopy() *OmniKubeconfigExportStatus {
	if in == nil {
		return nil
	}
	out := new(OmniKubeconfigExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniMachine) DeepCopyInto(out *OmniMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniMachine.
func (in *OmniMachine) DeepCopy() *OmniMachine {
	if in == nil {
		return nil
	}
	out := new(OmniMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniMachineList) DeepCopyInto(out *OmniMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniMachineList.
func (in *OmniMachineList) DeepCopy() *OmniMachineList {
	if in == nil {
		return nil
	}
	out := new(OmniMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniMachineSpec) DeepCopyInto(out *OmniMachineSpec) {
	*out = *in
	in.Descriptors.DeepCopyInto(&out.Descriptors)
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(MachineInstallSpec)
		**out = **in
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]Patch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SystemExtensions != nil {
		in, out := &in.SystemExtensions, &out.SystemExtensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KernelArgs != nil {
		in, out := &in.KernelArgs, &out.KernelArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniMachineSpec.
func (in *OmniMachineSpec) DeepCopy() *OmniMachineSpec {
	if in == nil {
		return nil
	}
	out := new(OmniMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniMachineStatus) DeepCopyInto(out *OmniMachineStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniMachineStatus.
func (in *OmniMachineStatus) DeepCopy() *OmniMachineStatus {
	if in == nil {
		return nil
	}
	out := new(OmniMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSecretSync) DeepCopyInto(out *OmniSecretSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSecretSync.
func (in *OmniSecretSync) DeepCopy() *OmniSecretSync {
	if in == nil {
		return nil
	}
	out := new(OmniSecretSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniSecretSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSecretSyncList) DeepCopyInto(out *OmniSecretSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniSecretSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSecretSyncList.
func (in *OmniSecretSyncList) DeepCopy() *OmniSecretSyncList {
	if in == nil {
		return nil
	}
	out := new(OmniSecretSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniSecretSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSecretSyncSpec) DeepCopyInto(out *OmniSecretSyncSpec) {
	*out = *in
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	out.KubeconfigSecretRef = in.KubeconfigSecretRef
	out.SourceSecretRef = in.SourceSecretRef
	out.TargetSecretRef = in.TargetSecretRef
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSecretSyncSpec.
func (in *OmniSecretSyncSpec) DeepCopy() *OmniSecretSyncSpec {
	if in == nil {
		return nil
	}
	out := new(OmniSecretSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniSecretSyncStatus) DeepCopyInto(out *OmniSecretSyncStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniSecretSyncStatus.
func (in *OmniSecretSyncStatus) DeepCopy() *OmniSecretSyncStatus {
	if in == nil {
		return nil
	}
	out := new(OmniSecretSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniWorkers) DeepCopyInto(out *OmniWorkers) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniWorkers.
func (in *OmniWorkers) DeepCopy() *OmniWorkers {
	if in == nil {
		return nil
	}
	out := new(OmniWorkers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniWorkers) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniWorkersList) DeepCopyInto(out *OmniWorkersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OmniWorkers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniWorkersList.
func (in *OmniWorkersList) DeepCopy() *OmniWorkersList {
	if in == nil {
		return nil
	}
	out := new(OmniWorkersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OmniWorkersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniWorkersSpec) DeepCopyInto(out *OmniWorkersSpec) {
	*out = *in
	in.MachineSetSpecFields.DeepCopyInto(&out.MachineSetSpecFields)
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(UpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.UpgradeStrategy != nil {
		in, out := &in.UpgradeStrategy, &out.UpgradeStrategy
		*out = new(UpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.DeleteStrategy != nil {
		in, out := &in.DeleteStrategy, &out.DeleteStrategy
		*out = new(UpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniWorkersSpec.
func (in *OmniWorkersSpec) DeepCopy() *OmniWorkersSpec {
	if in == nil {
		return nil
	}
	out := new(OmniWorkersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OmniWorkersStatus) DeepCopyInto(out *OmniWorkersStatus) {
	*out = *in
	in.CommonStatusFields.DeepCopyInto(&out.CommonStatusFields)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OmniWorkersStatus.
func (in *OmniWorkersStatus) DeepCopy() *OmniWorkersStatus {
	if in == nil {
		return nil
	}
	out := new(OmniWorkersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Patch) DeepCopyInto(out *Patch) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Patch.
func (in *Patch) DeepCopy() *Patch {
	if in == nil {
		return nil
	}
	out := new(Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingStrategy) DeepCopyInto(out *RollingStrategy) {
	*out = *in
	if in.MaxParallelism != nil {
		in, out := &in.MaxParallelism, &out.MaxParallelism
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingStrategy.
func (in *RollingStrategy) DeepCopy() *RollingStrategy {
	if in == nil {
		return nil
	}
	out := new(RollingStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncKubeconfigSecretRef) DeepCopyInto(out *SecretSyncKubeconfigSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncKubeconfigSecretRef.
func (in *SecretSyncKubeconfigSecretRef) DeepCopy() *SecretSyncKubeconfigSecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretSyncKubeconfigSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncSourceSecretRef) DeepCopyInto(out *SecretSyncSourceSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncSourceSecretRef.
func (in *SecretSyncSourceSecretRef) DeepCopy() *SecretSyncSourceSecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretSyncSourceSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncTargetSecretRef) DeepCopyInto(out *SecretSyncTargetSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncTargetSecretRef.
func (in *SecretSyncTargetSecretRef) DeepCopy() *SecretSyncTargetSecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretSyncTargetSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStatusFields) DeepCopyInto(out *SyncStatusFields) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStatusFields.
func (in *SyncStatusFields) DeepCopy() *SyncStatusFields {
	if in == nil {
		return nil
	}
	out := new(SyncStatusFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosSpec) DeepCopyInto(out *TalosSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosSpec.
func (in *TalosSpec) DeepCopy() *TalosSpec {
	if in == nil {
		return nil
	}
	out := new(TalosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategy) DeepCopyInto(out *UpdateStrategy) {
	*out = *in
	if in.Rolling != nil {
		in, out := &in.Rolling, &out.Rolling
		*out = new(RollingStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategy.
func (in *UpdateStrategy) DeepCopy() *UpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategy)
	in.DeepCopyInto(out)
	return out
}
