apiVersion: v2
name: omni-cluster-operator-crds
description: CustomResourceDefinitions for the Omni Cluster Operator.
type: application
version: 0.0.0
appVersion: 0.0.0
home: https://github.com/texas-hpc/omni-cluster-operator
sources:
  - https://github.com/texas-hpc/omni-cluster-operator
keywords:
  - omni
  - talos
  - kubernetes
  - operator
  - crds
maintainers:
  - name: Texas HPC
