apiVersion: v2
name: omni-cluster-operator
description: Kubernetes operator for managing Sidero Omni cluster lifecycles.
type: application
version: 0.0.0
appVersion: 0.0.0
home: https://github.com/texas-hpc/omni-cluster-operator
icon: https://texas-hpc.github.io/omni-cluster-operator/assets/patch-logo.png
annotations:
  artifacthub.io/license: Apache-2.0
sources:
  - https://github.com/texas-hpc/omni-cluster-operator
keywords:
  - omni
  - talos
  - kubernetes
  - operator
maintainers:
  - name: Texas HPC
