#!/usr/bin/env bash
#MISE description="Render the Helm chart."
set -euo pipefail

chart_version="${CHART_VERSION:-$(hack/mise/nbgv get-version -v SemVer2)}"
app_version="${APP_VERSION:-${chart_version}}"
image_repository="${IMAGE_REPOSITORY:-ghcr.io/texas-hpc/omni-cluster-operator}"
image_tag="${IMAGE_TAG:-${chart_version}}"

helm template omni-cluster-operator charts/omni-cluster-operator \
  --include-crds \
  --namespace omni-cluster-operator-system \
  --set "image.repository=${image_repository}" \
  --set "image.tag=${image_tag}" \
  --set "chartVersion=${chart_version}" \
  --set "appVersion=${app_version}"
