#!/usr/bin/env bash
#MISE description="Generate Helm chart README files."
set -euo pipefail

helm-docs \
  --chart-search-root charts \
  --template-files README.md.gotmpl \
  --sort-values-order file
