#!/usr/bin/env bash
#MISE description="Render the Helm charts."
set -euo pipefail

chart_version="${CHART_VERSION:-$(nbgv get-version -v SemVer2)}"
image_repository="${IMAGE_REPOSITORY:-ghcr.io/texas-hpc/omni-cluster-operator}"
image_tag="${IMAGE_TAG:-${chart_version}}"

helm template omni-cluster-operator-crds charts/omni-cluster-operator-crds \
  --include-crds \
  --namespace omni-cluster-operator-system

helm template omni-cluster-operator charts/omni-cluster-operator \
  --namespace omni-cluster-operator-system \
  --set "image.repository=${image_repository}" \
  --set "image.tag=${image_tag}"
