#!/usr/bin/env bash
#MISE description="Generate Kubernetes deepcopy code."
set -euo pipefail

year="${YEAR:-$(date +%Y)}"
controller-gen object:headerFile="hack/boilerplate.go.txt",year="${year}" paths="./..."
